# Nodes with values to reuse in the pipeline.
common_params:
  plugins:
  - &docker_plugin
    docker#v3.8.0:
      image: &ruby_version "ruby:3.2.2"
      propagate-environment: true
      environment:
        - "RUBYGEMS_API_KEY"

steps:
  #################
  # Build and Test
  #################
  - group: 🧪 Build and Test"
    key: test
    steps:
      - label: "🧪 Build and Test"
        command: |
          echo "--- :rubygems: Setting up Gems"
          install_gems

          echo "--- :rspec: Run Rspec"
          bundle exec rspec --profile 10 --format progress
        plugins:
          - automattic/a8c-ci-toolkit#2.18.1
          - *docker_plugin
        agents:
          queue: "default"

  #################
  # Lint
  #################
  - label: "🧹 Lint (Rubocop)"
    key: rubocop
    command: |
      echo "--- :rubygems: Setting up Gems"
      install_gems

      echo "--- :rubocop: Run Rubocop"
      bundle exec rubocop
    plugins: [*docker_plugin]
    agents:
      queue: "default"
